### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by itsmitul9** [gophercises/quiz#102]
```
$ go build . && ./quiz -csv=problems.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.parseLines(0xc00000c030, 0x1, 0x1, 0x1, 0x0, 0x0)
        /home/mitul/go/src/gophercises/quiz/main.go:44 +0x14f
main.main()
        /home/mitul/go/src/gophercises/quiz/main.go:24 +0x2d9
```
facing run time error after running the solution 1 , i've not gone through the solution 2 video yet 
But looking for an answer for why this error happening ?

**Comment by itsmitul9** [comment]
[problems.csv](https://github.com/gophercises/quiz/files/7167594/problems.csv)

just figured it out, in probelms.csv ,(comma) was missing between integer 
correct format should be 5+5,10
